- name: Demoonvars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
   - name: printvariable
     ansible.builtin.debug:
      msg: URL_PLAY-{{URL_PLAY}}
   - name: printtaskvariable
     ansible.builtin.debug:
      msg: URL_TASK-{{URL_TASK}}
     vars:
      URL_TASK: Task.example.com
  roles:
    - demo
